### PR TITLE
Update MainForm.cs

### PR DESCRIPTION
**Pull request by mpinnuck**
Current version throws exception updating from non uni thread when clicking on the left and right arrows

### CODE REVIEW

**Comment by jlecomte** [comment]
Oh, interesting! I don't have any issue, but the change makes sense, so I will go ahead and merge it. Thank you for the contribution!

**Comment by jlecomte** [comment]
@mpinnuck Hey Mark, I fixed a syntax error that was in your PR and published a new version (`v1.1.0-patch2`). Also, thank you so much for your generous financial contribution, I really appreciate it!

**Comment by mpinnuck** [comment]
If you click the arrows often enough it will throw an unhandled exception. You must update the gui in the gui thread. Great product and engineering art.I built one and works very well RegardsMarkSent from my iPhoneOn 10 Mar 2024, at 5:28 am, Julien Lecomte ***@***.***> wrote:﻿
Oh, interesting! I don't have any issue, but the change makes sense, so I will go ahead and merge it. Thank you for the contribution!

**Comment by mpinnuck** [comment]
I have changed on my computer, but did the PR on on my phone.Sent from my iPhoneOn 10 Mar 2024, at 6:24 am, Julien Lecomte ***@***.***> wrote:﻿
@mpinnuck Hey Mark, I fixed a syntax error that was in your PR and published a new version (v1.1.0-patch2). Also, thank you so much for your generous financial contribution, I really appreciate it!

**Pull request merged**
